# Generated by Django 3.0.2 on 2020-02-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RtzCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('rtz_id', models.BigIntegerField()),
                ('comment', models.CharField(max_length=512)),
                ('like', models.IntegerField(default='0')),
                ('dislike', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='RtzModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=64, unique=True)),
                ('family', models.CharField(max_length=64)),
                ('person_name', models.CharField(max_length=64)),
                ('tags', models.CharField(max_length=256)),
                ('views', models.IntegerField(default='0')),
                ('comments', models.IntegerField(default='0')),
                ('marks', models.IntegerField(default='0')),
            ],
        ),
    ]
