# Generated by Django 3.0.2 on 2020-02-03 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RtzModel',
            new_name='Rtz',
        ),
        migrations.RenameModel(
            old_name='RtzCommentModel',
            new_name='RtzComment',
        ),
    ]
