# Generated by Django 3.0.2 on 2020-02-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.BigIntegerField(default=1580539277720),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='update_time',
            field=models.BigIntegerField(default=1580539277720),
        ),
    ]
