# Generated by Django 3.0.2 on 2020-02-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200203_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.BigIntegerField(default=1580702524298),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='update_time',
            field=models.BigIntegerField(default=1580702524298),
        ),
    ]
